### PR TITLE
Remove template provider

### PR DESCRIPTION
**Pull request by bwmetcalf**
## what
* Remove deprecated template provider

## why
* Provider is deprecated

### CODE REVIEW

**Comment by bwmetcalf** [comment]
@Gowiem Thanks!

**Review by Gowiem — APPROVED** [review]
LGTM 👍

cc @nitrocode as he had asked for file changes in the original fix branch #19

**Comment by bwmetcalf** [comment]
@Gowiem Anything I can assist with to get this merged?  Thanks.

**Comment by Gowiem** [comment]
@bwmetcalf it's continuing to fail with the same error. I'll surface internally and will see if anyone has seen that one before. Thanks for the follow up -- Be sure to do so again if you don't hear from me 😅

**Comment by beahues** [comment]
From reading a lot of https://github.com/actions/checkout/issues/760 it appears because of https://github.blog/2022-04-12-git-security-vulnerability-announced/

the fix is being run in one of the earlier steps at https://github.com/cloudposse/actions/actions/runs/3223644469/jobs/5273940946#step:5:25 but for some reason doesn't appear to be being consumed in https://github.com/cloudposse/actions/actions/runs/3223644469/jobs/5273940946#step:9:61 I don't know if the running of git commands in a way that ignores the global config?

Maybe adding the `safe.directory` fix to the `terratest` job in https://github.com/cloudposse/actions/blob/master/.github/workflows/test-command.yml ?

**Pull request closed without merging**
